import React from 'react';

function Chapter1() {
    return (
      <div className="Chapters" style={{ wordBreak: "break-all"}}>
        <h3>Contexto general</h3>
        <h4>Contexto general</h4>
        <p>rellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenoellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenoellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorellenorelleno</p>
      </div>
    );
  }

export default Chapter1;
